#!/usr/bin/env bash
# setup to load balancer
add-apt-repository -y ppa:vbernat/haproxy-1.5
apt-get update
apt-get install -y haproxy

echo -e "frontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back\n" >> /etc/haproxy/haproxy.cfg
echo -e "backend http_back\n\tbalance roundrobin\n\tserver 394-web-01 35.231.156.161:80 check\n\tserver 394-web-02 34.73.64.44:80 check" >> /etc/haproxy/haproxy.cfg

service haproxy restart
