#!/usr/bin/env bash
# configure a load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo service haproxy start

echo 'frontend theproxy
        bind *:80
	default_backend my_backend_servers

backend my_backend_servers
	balance roundrobin
	server 236369-web-01 18.209.180.135:80
	server 236369-web-02 54.165.237.14:80' | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy reload
