#!/usr/bin/env bash
# This script displays the ff;
# To infinity and beyond indefinitely
# With sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
