#!/usr/bin/env bash
# This script displays the following;
# display hours from 0 to 12
# display minutes from 1 to 59
i=0
j=1


while [ $i -le 12 ]; do
	echo "Hour: $i"
	while [ $i -le 59 ]; do
		echo $j
		j=$((j+1))
	done
	j=$((1))
	i=$((i+1))
done
