#!/usr/bin/env bash
# This script displays the following;
# The content of the current working directory
# In a list format
# Where only the part of the name after the first dash is diplayed

for f in *; do
	echo "$f" | cut -d '-' -f 2
done
