#!/usr/bin/env bash
# This script run nginx as nginx user not root user

# Kill the apache2 server
sudo pkill -f apache2

sleep 10

# Change the permissions on the configuration file
sudo chmod 777 /etc/nginx/nginx.conf

# update the listening ports
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default

# restart the nginx server
sudo service nginx restart
